
[app:main]
use = egg:backend

pyramid.reload_templates = true
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false

; sqlalchemy.url = postgresql://postgres:root@192.168.18.91:5432/db_matakuliah_122140092
sqlalchemy.url = postgresql+psycopg2://postgres:root@192.168.18.91:5432/db_matakuliah_122140092

[server:main]
use = egg:waitress#main
listen = localhost:6543

